"""User administration: the current user, listing, details, creation, updates."""

from __future__ import annotations

from typing import Any

from mcp_redmine.app import get_client, tool
from mcp_redmine.format import dumps

# 1 = active, 2 = registered awaiting activation, 3 = locked
USER_STATUSES = {1: "active", 2: "registered (awaiting activation)", 3: "locked"}


@tool
def get_current_user() -> str:
    """Return the user that owns the API key configured on this server.

    Useful for confirming which identity issues are being created under, and
    whether that user is an administrator.
    """
    data = get_client().request("GET", "/users/current.json")
    u = data.get("user", {})
    return dumps(
        {
            "id": u.get("id"),
            "login": u.get("login"),
            "name": f"{u.get('firstname', '')} {u.get('lastname', '')}".strip(),
            "email": u.get("mail"),
            "admin": u.get("admin"),
            "created_on": u.get("created_on"),
        }
    )


@tool
def list_users(status: int = 1, name: str = "", limit: int = 50) -> str:
    """List Redmine users.

    Requires administrator privileges.

    Args:
        status: 1 = active, 2 = registered awaiting activation, 3 = locked.
        name: filter by login, first name, last name, or email (partial
            match).
        limit: maximum number of users returned.
    """
    params: dict[str, Any] = {"status": status, "limit": limit}
    if name:
        params["name"] = name

    data = get_client().request("GET", "/users.json", params=params)

    users = [
        {
            "id": u["id"],
            "login": u.get("login"),
            "name": f"{u.get('firstname', '')} {u.get('lastname', '')}".strip(),
            "email": u.get("mail"),
            "admin": u.get("admin"),
        }
        for u in data.get("users", [])
    ]
    return dumps(users)


@tool
def get_user(user_id: int) -> str:
    """Show a user's details.

    Includes which projects they belong to and with which role.

    Args:
        user_id: user ID.
    """
    data = get_client().request(
        "GET", f"/users/{user_id}.json?include=memberships,groups"
    )
    return dumps(data.get("user", {}))


@tool
def create_user(
    login: str,
    firstname: str,
    lastname: str,
    email: str,
    admin: bool = False,
    send_information: bool = True,
) -> str:
    """Create a user. Requires administrator privileges.

    The password is generated by Redmine itself and emailed to the person —
    this tool deliberately does not accept a password as a parameter, so no
    credential ever passes through the conversation. To set the password
    manually instead, use the Redmine web UI.

    Args:
        login: username for authentication.
        firstname: first name.
        lastname: last name.
        email: email address, also used to send the credentials.
        admin: grants administrator privileges.
        send_information: sends the email with the generated password. Only
            turn this off if you'll set the password another way — without
            it, the person cannot log in.
    """
    payload = {
        "login": login,
        "firstname": firstname,
        "lastname": lastname,
        "mail": email,
        "admin": admin,
        "generate_password": True,
    }
    body: dict[str, Any] = {"user": payload}
    if send_information:
        body["send_information"] = True

    data = get_client().request("POST", "/users.json", json=body)

    u = data.get("user", {})
    return dumps(
        {
            "id": u.get("id"),
            "login": u.get("login"),
            "name": f"{u.get('firstname', '')} {u.get('lastname', '')}".strip(),
            "email": u.get("mail"),
            "admin": u.get("admin"),
            "password": "generated by Redmine"
            + (" and emailed" if send_information else ", NOT emailed"),
        }
    )


@tool
def update_user(
    user_id: int,
    login: str = "",
    firstname: str = "",
    lastname: str = "",
    email: str = "",
    status: int = 0,
    admin: int = -1,
) -> str:
    """Update a user. Requires administrator privileges.

    Locking is the reversible alternative to deletion: the user loses access
    but everything they created stays attributed to them. This server does
    not expose user deletion for that reason — deleting for real is still a
    web UI operation.

    Args:
        user_id: user ID.
        login: new login (empty = leave alone).
        firstname: new first name (empty = leave alone).
        lastname: new last name (empty = leave alone).
        email: new email (empty = leave alone).
        status: 1 = active, 3 = locked (0 = leave alone).
        admin: 1 grants, 0 revokes, -1 leaves alone.
    """
    if status and status not in USER_STATUSES:
        return f"Invalid status: {status}. Use 1 (active) or 3 (locked)."

    payload: dict[str, Any] = {}
    if login:
        payload["login"] = login
    if firstname:
        payload["firstname"] = firstname
    if lastname:
        payload["lastname"] = lastname
    if email:
        payload["mail"] = email
    if status:
        payload["status"] = status
    if admin in (0, 1):
        payload["admin"] = bool(admin)

    if not payload:
        return f"Nothing to update on user #{user_id}: no field was provided."

    get_client().request("PUT", f"/users/{user_id}.json", json={"user": payload})

    summary = ", ".join(sorted(payload))
    if status:
        summary += f" (now {USER_STATUSES[status]})"
    return f"User #{user_id} updated: {summary}."


@tool
def update_my_account(
    firstname: str = "",
    lastname: str = "",
    email: str = "",
) -> str:
    """Update the account of the user that owns the API key.

    Args:
        firstname: new first name (empty = leave alone).
        lastname: new last name (empty = leave alone).
        email: new email (empty = leave alone).
    """
    payload = {}
    if firstname:
        payload["firstname"] = firstname
    if lastname:
        payload["lastname"] = lastname
    if email:
        payload["mail"] = email

    if not payload:
        return "Nothing to update: no field was provided."

    get_client().request("PUT", "/my/account.json", json={"user": payload})
    return f"Account updated: {', '.join(sorted(payload))}."
